default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  primary:
    <<: *default
    database: rpgonrails_dev
  queue:
    <<: *default
    database: rpgonrails_dev_queue
    migrations_paths: db/queue_migrate

test:
  primary:
    <<: *default
    database: rpgonrails_test
  queue:
    <<: *default
    database: rpgonrails_test_queue
    migrations_paths: db/queue_migrate

production:
  primary:
    <<: *default
    database: rpgonrails_production
  queue:
    <<: *default
    database: rpgonrails_production_queue
    migrations_paths: db/queue_migrate
